[Features]Quantize pipeline
open-mmlab/mmrazor pull request #350
Opened 2022-11-15 13:37 UTC by HIT-cwh

Thanks for your contribution and we appreciate it a lot. The following instructions would make your pull request more healthy and more easily get feedback. If you do not understand some items, don't worry, just make the pull request and seek help from maintainers.

## Motivation

Please describe the motivation of this PR and the goal you want to achieve through this PR.

## Modification

Please briefly describe what modification is made in this PR.

## BC-breaking (Optional)

Does the modification introduce changes that break the backward compatibility of the downstream repositories?
If so, please describe how it breaks the compatibility and how the downstream projects should modify their code to keep compatibility with this PR.

## Use cases (Optional)

If this PR introduces a new feature, it is better to list some use cases here and update the documentation.

## Checklist

**Before PR**:

- [ ] Pre-commit or other linting tools are used to fix the potential lint issues.
- [ ] Bug fixes are fully covered by unit tests, the case that causes the bug should be added in the unit tests.
- [ ] The modification is covered by complete unit tests. If not, please add more unit tests to ensure the correctness.
- [ ] The documentation has been modified accordingly, like docstring or example tutorials.

**After PR**:

- [ ] If the modification has potential influence on downstream or other related projects, this PR should be tested with those projects, like MMDet or MMSeg.
- [ ] CLA has been signed and all committers have signed the CLA in this PR.

2022-11-22 10:21 UTC, humu789 requested changes

2022-11-22 10:21 UTC, humu789 commented on mmrazor/engine/runner/quantization_loops.py
>                  self.runner.val_loop.run()
在训练结束后应该再进行 convert + val，convert 成inference模式再测精度更能准确描述量化模型的实际精度

2022-11-23 11:36 UTC, HIT-cwh commented on configs/quantization/qat/lsq_resnet18_8xb32_in1k.py
> +        type='TensorRTQuantizer',
现在TensorRTQuantizer和CustomQuantizer的差距只差了个qconfig

2022-11-23 11:38 UTC, HIT-cwh commented on mmrazor/engine/runner/quantization_loops.py
> +        for idx, data_batch in enumerate(self.dataloader):
感觉ptq还得再讨论下怎么设计接口，目前主要支持了qat

2022-11-23 11:41 UTC, HIT-cwh commented on mmrazor/engine/runner/quantization_loops.py
> +        metrics = self.evaluator.evaluate(len(self.dataloader.dataset))
目前convert后的模型inference会报错，还在debug

2022-11-23 11:46 UTC, HIT-cwh commented on mmrazor/models/algorithms/quantization/base.py
> +        self._fake_quants_enabled = True
_observers_enabled _fake_quants_enabled是不是应该只能通过GeneralQuant来改呢？通过state.setter

2022-11-25 04:23 UTC, humu789 commented on configs/quantization/qat/lsq_resnet18_8xb32_in1k.py
> +        type='TensorRTQuantizer',
是的，我的意思后面TensorRTQuantizer会有较大修改，这里最好先用CustomQuantizer，你这个是用来验证pipeline的，优先保证实验稳定可复现，避免后续改动造成影响

2022-11-25 04:24 UTC, humu789 commented on mmrazor/engine/runner/quantization_loops.py
> +        for idx, data_batch in enumerate(self.dataloader):
那这个可以留着后面再改的

2022-11-25 04:25 UTC, humu789 commented on mmrazor/engine/runner/quantization_loops.py
> +        metrics = self.evaluator.evaluate(len(self.dataloader.dataset))
那我先把这个问题弄成待解决项

2022-11-25 04:27 UTC, humu789 commented on mmrazor/models/algorithms/quantization/base.py
> +        self._fake_quants_enabled = True
这个得先改了，原来的设计是通过algorithm这个层面修改state的。
现在的主要问题是 _observers_enabled -> observers_enabled；修改state的动作实际是在基类里通过self.observers_enabled属性实现的
_fake_quants_enabled同理

2022-11-25 07:20 UTC, humu789 approved these changes
整体没有什么问题，考虑到整体进度，有些小的comments可以后续再修。

2022-11-25 07:45 UTC, merged