[Refactor & Doc] Refactor graph_utils and add docstring and pytest
open-mmlab/mmrazor pull request #420
Opened 2023-01-03 11:19 UTC by HIT-cwh

## Modification

1. Refactor graph_utils: We support deleting fakequant before / after  op / method / function / module in graph_utils.
2. Add 8 properties to `BaseQuantizer`. Each is a tuple. For example, the `module_del_prev_fakequant` property in `OpenVINOQuantizer` is (torch.nn.ReLU6, torch.nn.Identity). These properties are determined by the backend, so maybe they need to be regarded as properties.
3. Add the corresponding pytest and docstring.

2023-01-05 03:55 UTC, humu789 reviewed
删除fakequant的定位应该是graph后处理，属于可选操作，是qconfig_mapping和backendconfig机制确定量化graph和量化策略的补充，另外这个删除fakequant机制对网络的泛化也有待验证，整体感觉作为可配置更合适，另外之前实验也表明，graph出入一两个fakequant其实对性能影响不大的，不太适合和backend强行绑定

2023-01-05 03:55 UTC, humu789 commented on mmrazor/models/quantizers/base.py
> +    def del_fakequant(self, prepared):
del_fakequant不是必需的操作，感觉不是很适合放基类里，另外新增的几个属性如module_del_prev_fakequant 粒度较小，也不是很适合直接作为quantizer的属性

2023-01-05 06:37 UTC, pppppM requested changes
I have discussed this PR with @humu789, and the conclusion is different from his previous review

1. Replace the `remove_fakequants` config with the new properties.
2. Move the `del_fakequant` and the new properties to `NativeQuantizer`. `NativeQuantizer` is the base class of various backend, and `AcedamicQuantizer` don't need del fakequant
3. The `prepare` in `OpenvinoQuantizer` should move to `NativeQuantizer`.

2023-01-05 06:37 UTC, pppppM commented on mmrazor/models/quantizers/base.py
> +            prepared, self.module_del_prev_fakequant, inplace=True)
```suggestion
        extra_module_del_prev_fakequant = self.extra_redundant_fakequants.get('module_del_prev_fakequant', tuple())
        prepared = del_fakequant_before_module(
            prepared, self.module_del_prev_fakequant + extra_module_del_prev_fakequant , inplace=True)
```
There may be some redundant fakequant due to the model, not the backend

2023-01-05 06:37 UTC, pppppM commented on mmrazor/models/quantizers/base.py
> +    def del_fakequant(self, prepared):
del_fakequant -> del_redundant_fakequant

2023-01-05 06:37 UTC, pppppM commented on mmrazor/models/quantizers/base.py
> +    def module_del_prev_fakequant(self):
How about `module_prev_wo_fakequant`?

2023-01-09 02:53 UTC, HIT-cwh commented on mmrazor/models/quantizers/base.py
> +    def module_del_prev_fakequant(self):
Good point.

2023-01-09 05:58 UTC, humu789 approved these changes

2023-01-09 06:39 UTC, pppppM approved these changes

2023-01-09 06:39 UTC, merged