Quantize
open-mmlab/mmrazor pull request #425
Opened 2023-01-06 06:23 UTC by 415905716

Thanks for your contribution and we appreciate it a lot. The following instructions would make your pull request more healthy and more easily get feedback. If you do not understand some items, don't worry, just make the pull request and seek help from maintainers.

## Motivation

Please describe the motivation of this PR and the goal you want to achieve through this PR.

## Modification

Please briefly describe what modification is made in this PR.

## BC-breaking (Optional)

Does the modification introduce changes that break the backward compatibility of the downstream repositories?
If so, please describe how it breaks the compatibility and how the downstream projects should modify their code to keep compatibility with this PR.

## Use cases (Optional)

If this PR introduces a new feature, it is better to list some use cases here and update the documentation.

## Checklist

**Before PR**:

- [ ] Pre-commit or other linting tools are used to fix the potential lint issues.
- [ ] Bug fixes are fully covered by unit tests, the case that causes the bug should be added in the unit tests.
- [ ] The modification is covered by complete unit tests. If not, please add more unit tests to ensure the correctness.
- [ ] The documentation has been modified accordingly, like docstring or example tutorials.

**After PR**:

- [ ] If the modification has potential influence on downstream or other related projects, this PR should be tested with those projects, like MMDet or MMSeg.
- [ ] CLA has been signed and all committers have signed the CLA in this PR.

2023-01-06 06:59 UTC, pppppM requested changes
- `configs/quantization/qat/base_openvino_resnet18_8*b32_in1k.py` should be `configs/quantization/qat/minmax_openvino_resnet18_8xb32_in1k.py`.
The first place of the config name should be the algorithm name, and `*` should use `x`.

- Remove `dist_ptq.sh`. We don't plan to support dist ptq
- Complete arg descriptions. Some arg descriptions maybe generated by the plugin,  don't have real context

2023-01-06 06:59 UTC, pppppM commented on mmrazor/models/algorithms/quantization/mm_architecture.py
> +            pdb.set_trace()
del

2023-01-06 06:59 UTC, pppppM commented on mmrazor/models/algorithms/quantization/mm_architecture.py
> +            different graph of quantized model.
Add a note to explain why we need to generate multi graph

2023-01-06 06:59 UTC, pppppM commented on mmrazor/models/quantizers/native_quantizer.py
>          graph_module = _fuse_fx(
Explain what happened after `_fuse_fx` and after `prepare`

2023-01-06 06:59 UTC, pppppM commented on mmrazor/models/quantizers/native_quantizer.py
> +
Explain why we need to `post_process_weight_fakequant`

2023-01-06 06:59 UTC, pppppM commented on mmrazor/models/quantizers/native_quantizer.py
> +                    # `to_float()` function fuse BN into conv or conv_relu.
`to_float()` is not only fuse BN but also will convert a qat module to a normal module.

Add `to_float()` source code url

2023-01-06 06:59 UTC, pppppM commented on mmrazor/models/quantizers/native_quantizer.py
> +                    # explicitly keep the fake quant structure, others don't.
```suggestion
                    # This is decided by backend type, some backend need
                    # explicitly keep the fake quant structure, others don't.
                    # TODO add deploy doc link
```

2023-01-06 06:59 UTC, pppppM commented on configs/quantization/qat/base_openvino_resnet18_8*b32_in1k.py
> +
del

2023-01-12 10:13 UTC, humu789 requested changes
1. need to add some docstring and type hint
2. need to get the coverage of your added unittest

2023-01-12 10:13 UTC, humu789 commented on mmrazor/models/algorithms/quantization/mm_architecture.py
MMArchitectureQuantDDP need to add docstring and type hint

2023-01-12 10:13 UTC, humu789 commented on mmrazor/models/quantizers/native_quantizer.py
>                   tracer=dict(type='CustomTracer'),
` tracer` and `extra_redundant_fakequants` need to add type hint

2023-01-12 10:13 UTC, humu789 commented on mmrazor/models/quantizers/native_quantizer.py
>      def del_redundant_fakequant(self, prepared):
add docstring and type hint

2023-01-13 06:23 UTC, humu789 reviewed
`typing` used in type hint and docstring had better be consistent

2023-01-13 06:23 UTC, humu789 commented on mmrazor/models/algorithms/quantization/mm_architecture.py
> +    def _build_qmodels(self, model: dict):
`model` is not dict

2023-01-13 06:23 UTC, humu789 commented on mmrazor/models/algorithms/quantization/mm_architecture.py
> +        self.sync_qparams(forward_modes[1])
can not use `forward_modes[1]`, `len(forward_modes)` may be is 1 in ptq

2023-01-13 06:23 UTC, humu789 commented on mmrazor/models/quantizers/native_quantizer.py
> +                 no_observer_modules: Union[List, Tuple, None] = None,
`Union[List, Tuple, None]` -> `Optional[List]`

2023-01-13 07:11 UTC, humu789 approved these changes

2023-01-16 10:37 UTC, pppppM approved these changes

2023-01-17 03:19 UTC, merged