split dataset for greedynas
open-mmlab/mmrazor pull request #83
Opened 2022-02-16 09:23 UTC by humu789

## Motivation

split dataset for greedynas 

## Modification

Please briefly describe what modification is made in this PR.

## BC-breaking (Optional)

Does the modification introduce changes that break the backward compatibility of the downstream repositories?
If so, please describe how it breaks the compatibility and how the downstream projects should modify their code to keep compatibility with this PR.

## Use cases (Optional)

If this PR introduces a new feature, it is better to list some use cases here and update the documentation.

## Checklist

**Before PR**:

- [ ] Pre-commit or other linting tools are used to fix the potential lint issues.
- [ ] Bug fixes are fully covered by unit tests, the case that causes the bug should be added in the unit tests.
- [ ] The modification is covered by complete unit tests. If not, please add more unit tests to ensure the correctness.
- [ ] The documentation has been modified accordingly, like docstring or example tutorials.

**After PR**:

- [ ] If the modification has potential influence on downstream or other related projects, this PR should be tested with those projects, like MMDet or MMSeg.
- [ ] CLA has been signed and all committers have signed the CLA in this PR.

2022-03-22 05:40 UTC, pppppM requested changes

2022-03-22 05:40 UTC, pppppM commented on mmrazor/datasets/utils.py
> +def split_dataset_txt(txt_path, save_dir):
It is better to make a tool script and put it in the `tools/datasets`

2022-03-22 05:40 UTC, pppppM commented on mmrazor/datasets/utils.py
> +def split_dataset_txt(txt_path, save_dir):
It is better to make a tool script and put it in the `tools/datasets`

2022-03-22 05:40 UTC, pppppM commented on mmrazor/datasets/utils.py
> +    assert len(index_pool) == 1000
Pls add doc-string to show the `index_pool` example item

2022-03-22 05:40 UTC, pppppM commented on mmrazor/datasets/utils.py
> +    assert len(index_pool) == 1000
Pls add doc-string to show the `index_pool` example item

2022-03-22 05:40 UTC, pppppM commented on mmrazor/datasets/utils.py
> +        filenames_val = random.sample(filenames, 50)
The `50` seems should be an arg

2022-03-22 05:40 UTC, pppppM commented on mmrazor/datasets/utils.py
> +        filenames_val = random.sample(filenames, 50)
The `50` seems should be an arg

2022-03-22 05:40 UTC, pppppM commented on mmrazor/datasets/utils.py
> +    index_pool = dict()
`index_pool` -> `class2images` ?

2022-03-22 05:40 UTC, pppppM commented on mmrazor/datasets/utils.py
> +    index_pool = dict()
`index_pool` -> `class2images` ?

2022-03-22 05:40 UTC, pppppM commented on mmrazor/datasets/utils.py
> +    val_txt = list()
The `train/val_txt` should be `part_xx`.
This script can also be reused when supporting semi-supervised algorithms in the future.

2022-03-22 05:40 UTC, pppppM commented on mmrazor/datasets/utils.py
> +    val_txt = list()
The `train/val_txt` should be `part_xx`.
This script can also be reused when supporting semi-supervised algorithms in the future.

2022-03-22 05:40 UTC, pppppM commented on mmrazor/datasets/utils.py
> +            val_txt.append(f'{name} {index}')
The class-balanced sample should be configurable.
Some algorithms don't split the dataset in this way.

2022-03-22 05:40 UTC, pppppM commented on mmrazor/datasets/utils.py
> +            val_txt.append(f'{name} {index}')
The class-balanced sample should be configurable.
Some algorithms don't split the dataset in this way.

2022-03-22 05:40 UTC, pppppM commented on mmrazor/datasets/utils.py
> +    with open(os.path.join(save_dir, 'greedynas_train.txt'), 'w') as f:
`greedynas_train.txt` should be `train/val_part_1.txt` according to the  origin txt name

2022-03-22 05:40 UTC, pppppM commented on mmrazor/datasets/utils.py
> +    with open(os.path.join(save_dir, 'greedynas_train.txt'), 'w') as f:
`greedynas_train.txt` should be `train/val_part_1.txt` according to the  origin txt name

2022-03-22 05:40 UTC, pppppM commented on mmrazor/datasets/utils.py
> +    with open(os.path.join(save_dir, 'greedynas_val.txt'), 'w') as f:
`greedynas_val.txt` should be `train/val_part_2.txt` according to the  origin txt name

2022-03-22 05:40 UTC, pppppM commented on mmrazor/datasets/utils.py
> +    with open(os.path.join(save_dir, 'greedynas_val.txt'), 'w') as f:
`greedynas_train.txt` should be `train/val_part_2.txt` according to the  origin txt name

2022-03-23 20:12 UTC, humu789 commented on mmrazor/datasets/utils.py
> +def split_dataset_txt(txt_path, save_dir):
`split_imagenet_dataset` is better

2022-06-15 00:47 UTC, closed without merging